from os import path

# Game Screen
SCREEN_WIDTH  = 1280
SCREEN_HEIGHT = 640
SCREEN_SIZE   = (SCREEN_WIDTH, SCREEN_HEIGHT)
SCREEN_ORIGIN = (0, 0)

PICTURE_WIDTH  = 350
PICTURE_HEIGHT = 175
PICTURE_SIZE   = (PICTURE_WIDTH, PICTURE_HEIGHT)
PICTURE_ORIGIN = SCREEN_ORIGIN

# Game States
START_SCREEN = 1
GAME_SCREEN  = 2
LEAVE_GAME   = -1

# Game Sound
GAME_VOLUME = 0.05

# Player
PLAYER_RUNNING_SPEED = 3
PLAYER_JUMPING_SPEED = 8
PLAYER_DOUBLE_JUMPING_SPEED = 2
PLAYER_DASHING_SPEED = 6
PLAYER_DOUBLE_JUMPING_LIMIT = 1
PLAYER_FRAME_DELAY = 100
PLAYER_VOLUME = 0.05

# Frutas
FRUTAS_WIDTH = 0
FRUTAS_HEIGHT = 0

# Physics
GRAVITY = 1

# Direcotires
ASSETS_DIR = path.join(path.dirname(__file__), "assets")
IMAGES_DIR = path.join(ASSETS_DIR, "images")
SOUNDS_DIR = path.join(ASSETS_DIR, "sounds")


#Player states

STAND_BY = 0
JUMPING = 1
RUNNING = 2